---
- name: mdkir VimSrc
  become: true
  file:
    path: ~/VimSrc/
    state: directory
    mode: 0755

- name: scp or tar vim8.1
  become: true
  unarchive:
    src: files/v8.1.1766.tar.gz
    dest: ~/VimSrc/

- name: scp configure.sh
  become: true
  copy:
    src: "../{{ vim_config_file }}"
    dest: "{{ vim_path }}"
    mode: a+x


- name: vim configure
  become: true
  shell: "./configure.sh > log.txt chdir={{ vim_path }}"
  changed_when: true

- name: cat configure log
  command: cat {{ vim_path }}/log.txt
  register: vim_configure
  changed_when: true


- name: debug vim configure
  debug:
    msg: "{{ vim_configure.stdout_lines }}"

- name: import config-spacevim
  import_tasks: config-spacevim.yml
