---
- name: mdkir VimSrc 
  become: true
  file:
    path: ~/VimSrc/
    state: directory 
    mode: 0755


- name: scp or tar vim8.1
  become: true
  unarchive:
    src: ../files/v8.1.1766.tar.gz
    dest: ~/VimSrc/

- name: scp configure.sh
  become: true
  copy:
    src: "../{{ vim_config_file }}"
    dest: "{{ vim_path }}"
    mode: a+x


- name: vim configure
  become: true
  shell: 
    chdir: "{{ vim_path }}"
    cmd: "./configure.sh"
  register: vim_configure

- name: debug vim configure
  debug:
    msg: "{{ vim_configure.stdout_lines }}"

- name: install spacevim
  become: flase
  script: ../files/install_spacevim.sh
  register: spacevim_debug

- name: install spacevim_debug
  debug:
    msg: "{{ spacevim_debug.stdout_lines }}"
