---
- name: mdkir VimSrc
  become: true
  file:
    path: ~/VimSrc/
    state: directory
    mode: 0755

- name: scp or tar vim8.1
  become: true
  unarchive:
    src: files/v8.1.1766.tar.gz
    dest: ~/VimSrc/

- name: vim configure
  become: true
  script: files/configure.sh
    chdir: "{{ vim_path }}"
  register: vim_configure

- name: debug vim configure
  debug:
    msg: "{{ vim_configure.stdout_lines }}"

- name: import config-spacevim
  import_tasks: config-spacevim.yml