---
# tasks file for ansibles_vim



- name: system
  debug:
    msg: "{{ ansible_os_family }}.{{ ansible_distribution_major_version }}-{{ ansible_pkg_mgr }}"

# Install
- name: debian install spacevim
  include_tasks: setup-Debian.yml
  when: ansible_pkg_mgr == "apt"

- name: redhat install spacevim
  include_tasks: setup-RedHat.yml
  when: ansible_pkg_mgr == "yum"

- name: centos8 install spacevim
  include_tasks: setup-CentOs8.yml
  when: ansible_pkg_mgr == "dnf"
