---

- name: dnf update
  become: true
  dnf:
    name: "*"
    state: latest

- name: dnf remove vim
  become: true
  dnf:
    name: vim
    state: removed

- name: delete usr vim 
  become: true
  file:
    path: "/usr/local/vim8"
    state: absent

- name: dnf install defaults Software
  become: true
  dnf:
    name: "{{ dnf_packages }}"
    state: installed
  register: task_result

- name: pip3 install packages
  pip:
    name: "{{ pip3_packages }}"
    executable: pip3

- name: dnf install vim 
  become: true
  dnf:
    name: vim
    state: installed

- name: import config-spacevim
  import_tasks: config-spacevim.yml