---

- name: yum update
  become: true
  yum:
    name: "*"
    state: latest

- name: yum remove vim
  become: true
  yum:
    name: vim
    state: removed

- name: delete usr vim 
  become: true
  file:
    path: "/usr/local/vim8"
    state: absent

- name: yum install defaults Software
  become: true
  yum:
    name: "{{ yum_packages }}"
    state: installed
  register: task_result

- name: pip3 install packages
  pip:
    name: "{{ pip3_packages }}"
    executable: pip3

- name: scp or tar vim8.1
  become: true
  unarchive:
    src: ../files/v8.1.1766.tar.gz
    dest: ~/VimSrc/

