---
- name: Include OS-specific variables.
  include_vars: ../vars/Debian.yml

- name: apt update
  become: true
  apt:
    update_cache: yes

- name: apt upgrade
  become: true
  apt:
    upgrade: yes

- name: apt remove vim
  become: true
  apt:
    name: vim
    state: absent
    purge: yes

- name: delete usr vim 
  become: true
  file:
    path: "/usr/local/vim8"
    state: absent

- name: apt install defaults Software
  become: true
  apt:
    name: "{{ apt_packages }}"
    state: present
  register: task_result

- name: pip3 install packages
  pip:
    name: "{{ pip3_packages }}"
    executable: pip3

- name: import config-vim
  import_tasks: config-vim.yml







  



